[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'papercolor'
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
