[settings]
dotfiles.root = "~/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/mise/config.toml" = { source = "mise.toml" }
"~/.zshrc" = {}
"~/.gitconfig" = {}
"~/.tigrc" = {}
"~/.tmux.conf" = {}
"~/Brewfile" = {}
"~/.config/wezterm/wezterm.lua" = { source = "wezterm.lua" }
"~/.config/karabiner" = { source = "karabiner" }
"~/.config/nvim" = { source = "nvim" }

[env]
GOPATH = "~"
_.path = [
  "~/bin",
  "/opt/homebrew/bin",
  "/usr/local/sbin",
  "/usr/local/bin",  
]
