[settings]
dotfiles.root = "~/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/mise/config.toml" = "~/dotfiles/mise/config.toml"
"~/.zshrc" = {}
"~/.gitconfig" = {}
"~/.tigrc" = {}
"~/.tmux.conf" = {}
"~/Brewfile" = {}
"~/.config/wezterm/wezterm.lua" = "~/dotfiles/wezterm.lua"
"~/.config/karabiner" = "~/dotfiles/karabiner"
"~/.config/nvim" = "~/dotfiles/nvim"

[env]
GOPATH = "~"
_.path = [
  "~/bin",
  "/opt/homebrew/bin",
  "/usr/local/sbin",
  "/usr/local/bin",  
]
