name: Dotfiles CI
on:
  push:
    branches:
      - master
jobs:
  apply:
    name: Apply dotfiles
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: bash bin/install.sh
      - name: Make
        run: make test
