name: Dotfiles CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  apply:
    name: Apply dotfiles
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        run: bash bin/init.sh

